language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

before_script:
  - echo '============= gsbstart build ============'

script: android/gradlew app:build