name: F4LabCIBuildApk
on:
  push:
    tags:
      - release-v* # Push events to tags release-v1.0, release-v1.1.x

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          # same with pubspec.yaml
          flutter-version: "1.9.1+hotfix.2"
      - run: flutter pub get
      - run: flutter test --no-pub test/
      - run: flutter build apk
      - run: ls -l build/app/outputs/apk/release/app-release.apk
