name: F4LabCIRelease
on:
  push:
    tags:
      - "release-v*"

jobs:
  release-to-gitHub:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          # same with pubspec.yaml
          flutter-version: "1.9.1+hotfix.2"
      - run: flutter pub get
      - run: flutter analyze --no-pub --no-current-package lib/ test/
      - run: flutter test --no-pub test/
      - run: flutter build apk
      - uses: anton-yurchenko/git-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "false"
        with:
          args: |
            build/app/outputs/apk/release/app-release.apk
